version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=bug_report
    volumes:
      - /var/lib/mysql
      - ./bug_report.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    image: bug_report
    ports:
      - "8080:8080"
    depends_on:
      - mysql